# Generated by Django 4.1.8 on 2023-06-02 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_menuitems_is_seen_notification_receiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitems',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='menuitems',
            name='is_new_item',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menuitems',
            name='is_top_ordered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('customer', 'customer'), ('manager', 'manager'), ('owner', 'owner'), ('admin', 'admin')], default='customer', max_length=255),
        ),
    ]
